FROM golang:1.7-alpine

RUN apk --update add --no-cache --virtual .build-deps \
    gcc libc-dev linux-headers

COPY . /go/src/github.com/infobloxopen/container-ipam-tool
WORKDIR /go/src/github.com/infobloxopen/container-ipam-tool

RUN go build -o bin/create-ea-defs ./ea-defs
